import { describe, expect, it, vi, beforeEach } from "vitest";

const applicationFindMany = vi.fn();
const qualityMetricFindMany = vi.fn();
const trainerProfileFindUnique = vi.fn();
const payoutRequestGroupBy = vi.fn();
const supportTicketFindFirst = vi.fn();
const supportTicketCreate = vi.fn();
const auditLogCreate = vi.fn();

vi.mock("@/lib/db/prisma", () => ({
  prisma: {
    application: { findMany: (...a: unknown[]) => applicationFindMany(...a) },
    qualityMetric: { findMany: (...a: unknown[]) => qualityMetricFindMany(...a) },
    trainerProfile: { findUnique: (...a: unknown[]) => trainerProfileFindUnique(...a) },
    payoutRequest: { groupBy: (...a: unknown[]) => payoutRequestGroupBy(...a) },
    supportTicket: {
      findFirst: (...a: unknown[]) => supportTicketFindFirst(...a),
      create: (...a: unknown[]) => supportTicketCreate(...a),
    },
    auditLog: { create: (...a: unknown[]) => auditLogCreate(...a) },
  },
}));

const { detectStalledApplications, detectQualityDrops, detectPayoutFailures } = await import(
  "@/server/services/support-signals"
);

beforeEach(() => {
  applicationFindMany.mockReset().mockResolvedValue([]);
  qualityMetricFindMany.mockReset().mockResolvedValue([]);
  trainerProfileFindUnique.mockReset().mockResolvedValue(null);
  payoutRequestGroupBy.mockReset().mockResolvedValue([]);
  supportTicketFindFirst.mockReset().mockResolvedValue(null);
  supportTicketCreate.mockReset().mockResolvedValue({ id: "ticket-1" });
  auditLogCreate.mockReset().mockResolvedValue({});
});

describe("detectStalledApplications", () => {
  it("opens a ticket for a stalled application", async () => {
    applicationFindMany.mockResolvedValue([
      { userId: "user-1", status: "UNDER_REVIEW", updatedAt: new Date(Date.now() - 10 * 86_400_000) },
    ]);

    const created = await detectStalledApplications();

    expect(created).toBe(1);
    expect(supportTicketCreate).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          requesterId: "user-1",
          category: "ACCOUNT",
          signal: "stalled_application",
          autoGenerated: true,
        }),
      })
    );
  });

  it("skips a trainer already flagged for this signal", async () => {
    applicationFindMany.mockResolvedValue([
      { userId: "user-1", status: "SUBMITTED", updatedAt: new Date(Date.now() - 10 * 86_400_000) },
    ]);
    supportTicketFindFirst.mockResolvedValue({ id: "existing-ticket" });

    const created = await detectStalledApplications();

    expect(created).toBe(0);
    expect(supportTicketCreate).not.toHaveBeenCalled();
  });
});

describe("detectQualityDrops", () => {
  it("flags a trainer whose score dropped past the threshold", async () => {
    qualityMetricFindMany.mockResolvedValue([
      { trainerId: "profile-1", score: 0.6, recordedAt: new Date() },
      { trainerId: "profile-1", score: 0.85, recordedAt: new Date(Date.now() - 86_400_000) },
    ]);
    trainerProfileFindUnique.mockResolvedValue({ userId: "user-1" });

    const created = await detectQualityDrops();

    expect(created).toBe(1);
    expect(supportTicketCreate).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({ requesterId: "user-1", signal: "quality_drop" }),
      })
    );
  });

  it("ignores a trainer with only one recent snapshot", async () => {
    qualityMetricFindMany.mockResolvedValue([{ trainerId: "profile-1", score: 0.6, recordedAt: new Date() }]);

    const created = await detectQualityDrops();

    expect(created).toBe(0);
    expect(supportTicketCreate).not.toHaveBeenCalled();
  });

  it("ignores a drop smaller than the threshold", async () => {
    qualityMetricFindMany.mockResolvedValue([
      { trainerId: "profile-1", score: 0.8, recordedAt: new Date() },
      { trainerId: "profile-1", score: 0.85, recordedAt: new Date(Date.now() - 86_400_000) },
    ]);

    const created = await detectQualityDrops();

    expect(created).toBe(0);
    expect(supportTicketCreate).not.toHaveBeenCalled();
  });
});

describe("detectPayoutFailures", () => {
  it("flags a trainer at or above the failure threshold", async () => {
    payoutRequestGroupBy.mockResolvedValue([{ userId: "user-1", _count: 3 }]);

    const created = await detectPayoutFailures();

    expect(created).toBe(1);
    expect(supportTicketCreate).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({ requesterId: "user-1", category: "PAYMENT", signal: "payout_failures" }),
      })
    );
  });

  it("ignores a trainer below the failure threshold", async () => {
    payoutRequestGroupBy.mockResolvedValue([{ userId: "user-1", _count: 1 }]);

    const created = await detectPayoutFailures();

    expect(created).toBe(0);
    expect(supportTicketCreate).not.toHaveBeenCalled();
  });
});
