-- AlterTable
ALTER TABLE "support_tickets" ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "support_tickets" ADD COLUMN "signal" TEXT;

-- CreateIndex
CREATE INDEX "support_tickets_requesterId_signal_status_idx" ON "support_tickets"("requesterId", "signal", "status");
