import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { LifeBuoy, Radar } from "lucide-react";

import { auth } from "@/lib/auth";
import { prisma } from "@/lib/db/prisma";
import { can } from "@/lib/permissions/can";
import { PageHeader } from "@/components/shared/page-header";
import { KpiCard } from "@/components/shared/kpi-card";
import { EmptyState } from "@/components/shared/empty-state";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { StatusBadge } from "@/components/ui/badge-status";
import { Badge } from "@/components/ui/badge";
import { TicketActions } from "@/components/admin/ticket-actions";

export const metadata: Metadata = { title: "Support" };

const SIGNAL_LABELS: Record<string, string> = {
  stalled_application: "Stalled application",
  quality_drop: "Quality drop",
  payout_failures: "Payout failures",
};

export default async function AdminSupportPage() {
  const session = await auth();
  if (!session?.user) redirect("/login");
  const canAssign = can(session.user.roles, "support.assign");

  const [tickets, counts, autoFlaggedOpen, agents] = await Promise.all([
    prisma.supportTicket.findMany({
      include: { requester: true, assignee: true, messages: { take: 1, orderBy: { createdAt: "asc" } } },
      orderBy: { updatedAt: "desc" },
      take: 100,
    }),
    prisma.supportTicket.groupBy({ by: ["status"], _count: true }),
    prisma.supportTicket.count({ where: { autoGenerated: true, status: { notIn: ["RESOLVED", "CLOSED"] } } }),
    canAssign
      ? prisma.user.findMany({
          where: { roles: { some: { role: { key: "SUPPORT_AGENT" } } } },
          select: { id: true, firstName: true, lastName: true },
        })
      : Promise.resolve([]),
  ]);
  const countFor = (s: string) => counts.find((c) => c.status === s)?._count ?? 0;
  const agentOptions = agents.map((a) => ({ id: a.id, name: `${a.firstName} ${a.lastName}` }));

  return (
    <div className="space-y-6">
      <PageHeader
        title="Support tickets"
        description="Requests from trainers and clients, plus trainers automatically flagged by the support-signals scan."
      />
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
        <KpiCard label="Open" value={String(countFor("OPEN"))} icon={LifeBuoy} />
        <KpiCard label="Assigned" value={String(countFor("ASSIGNED"))} />
        <KpiCard label="Escalated" value={String(countFor("ESCALATED"))} trend={countFor("ESCALATED") > 0 ? "down" : "flat"} />
        <KpiCard label="Auto-flagged, open" value={String(autoFlaggedOpen)} icon={Radar} trend={autoFlaggedOpen > 0 ? "down" : "flat"} />
        <KpiCard label="Resolved" value={String(countFor("RESOLVED") + countFor("CLOSED"))} />
      </div>
      <Card>
        <CardContent className="pt-6 pb-6">
          {tickets.length === 0 ? <EmptyState icon={LifeBuoy} title="No tickets" description="Support requests appear here." /> : (
            <Table>
              <TableHeader><TableRow>
                <TableHead>Subject</TableHead><TableHead>Requester</TableHead><TableHead>Category</TableHead>
                <TableHead>Assignee</TableHead><TableHead>Opened</TableHead><TableHead>Status</TableHead>
                {canAssign ? <TableHead></TableHead> : null}
              </TableRow></TableHeader>
              <TableBody>
                {tickets.map((t) => (
                  <TableRow key={t.id}>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <p className="font-medium">{t.subject}</p>
                        {t.autoGenerated ? (
                          <Badge variant="info" className="gap-1">
                            <Radar className="size-3" /> {SIGNAL_LABELS[t.signal ?? ""] ?? "Auto-flagged"}
                          </Badge>
                        ) : null}
                      </div>
                      <p className="max-w-sm truncate text-xs text-muted-foreground">{t.messages[0]?.body}</p>
                    </TableCell>
                    <TableCell className="text-sm">{t.requester.firstName} {t.requester.lastName}</TableCell>
                    <TableCell className="text-xs">{t.category.replace(/_/g, " ").toLowerCase()}</TableCell>
                    <TableCell className="text-sm">{t.assignee ? `${t.assignee.firstName} ${t.assignee.lastName}` : "—"}</TableCell>
                    <TableCell className="text-xs text-muted-foreground">{t.createdAt.toLocaleDateString()}</TableCell>
                    <TableCell><StatusBadge status={t.status} /></TableCell>
                    {canAssign ? (
                      <TableCell className="text-right">
                        <TicketActions
                          ticketId={t.id}
                          currentUserId={session.user.id}
                          currentStatus={t.status}
                          isAssigned={Boolean(t.assigneeId)}
                          agents={agentOptions}
                        />
                      </TableCell>
                    ) : null}
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
