import { prisma } from "@/lib/db/prisma";

/** Applications sitting in a not-yet-decided status this long are flagged as stalled. */
const STALLED_APPLICATION_DAYS = 5;
/** Absolute drop in overall quality score (0–1 scale) that counts as "a drop" worth a human look. */
const QUALITY_DROP_THRESHOLD = 0.15;
/** How far back "recent" quality metrics are pulled, to bound the query and keep comparisons meaningful. */
const QUALITY_LOOKBACK_DAYS = 14;
/** Failed payout attempts within the lookback window before this fires. */
const PAYOUT_FAILURE_THRESHOLD = 2;
const PAYOUT_FAILURE_LOOKBACK_DAYS = 30;

type FlagResult = "created" | "already_open";

/**
 * Opens (or recognises an already-open) auto-generated support ticket for a
 * trainer a detector flagged. `requesterId` names the trainer the ticket is
 * about — there's no system/service-account user in this schema to
 * attribute it to instead, so it reads as "opened on their behalf."
 *
 * Deduped per (trainer, signal): a detector re-running daily must not pile
 * up a fresh ticket every day the underlying condition persists — one open
 * ticket per signal per trainer is the ceiling until someone resolves it.
 */
async function flagForSupport(params: {
  userId: string;
  category: "ACCOUNT" | "QUALITY_APPEAL" | "PAYMENT";
  signal: string;
  subject: string;
  body: string;
}): Promise<FlagResult> {
  const existing = await prisma.supportTicket.findFirst({
    where: {
      requesterId: params.userId,
      signal: params.signal,
      status: { notIn: ["RESOLVED", "CLOSED"] },
    },
    select: { id: true },
  });
  if (existing) return "already_open";

  const ticket = await prisma.supportTicket.create({
    data: {
      requesterId: params.userId,
      category: params.category,
      subject: params.subject,
      autoGenerated: true,
      signal: params.signal,
      messages: { create: { authorId: params.userId, body: params.body } },
    },
  });

  await prisma.auditLog.create({
    data: {
      // No human actor — this ticket was opened by the scheduled scan, not
      // a person acting on the account.
      actorId: null,
      action: "support_ticket.auto_flagged",
      entityType: "SupportTicket",
      entityId: ticket.id,
      metadata: { signal: params.signal, userId: params.userId },
    },
  });

  return "created";
}

/** Applications stuck in a pending-decision status past the stall threshold. */
export async function detectStalledApplications(): Promise<number> {
  const cutoff = new Date(Date.now() - STALLED_APPLICATION_DAYS * 86_400_000);

  const stalled = await prisma.application.findMany({
    where: {
      status: { in: ["SUBMITTED", "UNDER_REVIEW", "ADDITIONAL_INFO_REQUIRED"] },
      updatedAt: { lt: cutoff },
    },
    select: { userId: true, status: true, updatedAt: true },
  });

  let created = 0;
  for (const app of stalled) {
    const days = Math.floor((Date.now() - app.updatedAt.getTime()) / 86_400_000);
    const result = await flagForSupport({
      userId: app.userId,
      category: "ACCOUNT",
      signal: "stalled_application",
      subject: "Application awaiting review — stalled",
      body:
        `This application has been in ${app.status.replace(/_/g, " ").toLowerCase()} for ${days} days ` +
        `with no update. Flagged automatically so a reviewer can check in.`,
    });
    if (result === "created") created++;
  }
  return created;
}

/** Trainers whose overall quality score dropped sharply between their two most recent snapshots. */
export async function detectQualityDrops(): Promise<number> {
  const cutoff = new Date(Date.now() - QUALITY_LOOKBACK_DAYS * 86_400_000);

  const metrics = await prisma.qualityMetric.findMany({
    where: { category: "overall", recordedAt: { gte: cutoff } },
    orderBy: [{ trainerId: "asc" }, { recordedAt: "desc" }],
    select: { trainerId: true, score: true, recordedAt: true },
  });

  const byTrainer = new Map<string, typeof metrics>();
  for (const m of metrics) {
    const list = byTrainer.get(m.trainerId) ?? [];
    list.push(m);
    byTrainer.set(m.trainerId, list);
  }

  let created = 0;
  for (const [trainerId, snapshots] of byTrainer) {
    if (snapshots.length < 2) continue; // nothing to compare against yet
    const [latest, previous] = snapshots;
    const drop = previous.score - latest.score;
    if (drop < QUALITY_DROP_THRESHOLD) continue;

    const profile = await prisma.trainerProfile.findUnique({
      where: { id: trainerId },
      select: { userId: true },
    });
    if (!profile) continue;

    const result = await flagForSupport({
      userId: profile.userId,
      category: "QUALITY_APPEAL",
      signal: "quality_drop",
      subject: "Quality score dropped sharply",
      body:
        `Overall quality score fell from ${Math.round(previous.score * 100)}% to ${Math.round(latest.score * 100)}% ` +
        `between ${previous.recordedAt.toLocaleDateString()} and ${latest.recordedAt.toLocaleDateString()}. ` +
        `Flagged automatically in case something changed — a task type, working conditions, or a misunderstanding ` +
        `worth a conversation before it affects standing further.`,
    });
    if (result === "created") created++;
  }
  return created;
}

/** Trainers with repeated payout failures in the lookback window. */
export async function detectPayoutFailures(): Promise<number> {
  const cutoff = new Date(Date.now() - PAYOUT_FAILURE_LOOKBACK_DAYS * 86_400_000);

  const grouped = await prisma.payoutRequest.groupBy({
    by: ["userId"],
    where: { status: "FAILED", processedAt: { gte: cutoff } },
    _count: true,
  });

  let created = 0;
  for (const g of grouped) {
    if (g._count < PAYOUT_FAILURE_THRESHOLD) continue;

    const result = await flagForSupport({
      userId: g.userId,
      category: "PAYMENT",
      signal: "payout_failures",
      subject: "Repeated payout failures",
      body:
        `${g._count} payout attempts have failed in the last ${PAYOUT_FAILURE_LOOKBACK_DAYS} days. ` +
        `Likely a payment-method or provider issue blocking their earnings — flagged automatically for follow-up.`,
    });
    if (result === "created") created++;
  }
  return created;
}

export type SupportSignalScanResult = {
  stalledApplications: number;
  qualityDrops: number;
  payoutFailures: number;
  ticketsCreated: number;
};

/** Runs every detector once. Safe to call repeatedly — flagForSupport dedupes per (trainer, signal). */
export async function runSupportSignalScan(): Promise<SupportSignalScanResult> {
  const [stalledApplications, qualityDrops, payoutFailures] = await Promise.all([
    detectStalledApplications(),
    detectQualityDrops(),
    detectPayoutFailures(),
  ]);

  return {
    stalledApplications,
    qualityDrops,
    payoutFailures,
    ticketsCreated: stalledApplications + qualityDrops + payoutFailures,
  };
}
